In [1]:
import numpy as np
import gurobipy as gp

# Question 2 - Factory and Warehouse in Austin, Dallas

In [2]:
#max 9fa+5fd+6wa+4wd
obj = np.array([9,5,6,4])

A = np.zeros((3,4))
#Capital Needed
A[0,:] = [6,3,5,2]
#Factory
A[1,:] = [1,1,0,0]
#Warehouse
A[2,:] = [0,0,1,1]

b = np.array([11,1,1])
sense = ['<','>','<']

print(A,b)

[[6. 3. 5. 2.]
 [1. 1. 0. 0.]
 [0. 0. 1. 1.]] [11  1  1]


In [3]:
ipMod = gp.Model()
ipMod_x = ipMod.addMVar(len(obj),vtype=['B']*len(obj)) # 'C' or 'I' or 'B'
ipMod_con = ipMod.addMConstrs(A, ipMod_x, sense, b)
ipMod.setMObjective(None,obj,0,sense=gp.GRB.MAXIMIZE)

ipMod.Params.OutputFlag = 0 # tell gurobi to shut up!!
ipMod.optimize()

Academic license - for non-commercial use only - expires 2022-09-03
Using license file /Users/ramya/gurobi.lic


In [4]:
ipMod_x.x

array([1., 1., 0., 1.])

Answer: Factory in Dallas is part of optimal investment startegy

# Question 3 - Western Airlines Hub

In [5]:
#Minimize number of Hubs
obj = np.array([1,1,1,1,1,1,1,1,1,1,1,1])
A = np.zeros([12,12])
A[0,:] =  [1,0,1,0,1,0,1,1,1,0,0,0]
A[1,:] =  [0,1,0,0,0,0,0,1,1,0,0,0]
A[2,:] =  [1,0,1,0,0,0,1,1,1,0,0,0]
A[3,:] =  [0,0,0,1,0,0,0,0,0,1,0,0]
A[4,:] =  [1,0,0,0,1,0,1,0,0,0,0,0]
A[5,:] =  [0,0,0,0,0,1,0,0,0,1,1,0]
A[6,:] =  [1,0,1,0,1,0,1,0,0,0,0,0]
A[7,:] =  [1,1,1,0,0,0,0,1,1,0,0,0]
A[8,:] =  [1,1,1,0,0,0,0,1,1,0,0,0]
#SLC
A[9,:] =  [0,0,0,1,0,1,0,0,0,1,1,1]
A[10,:] = [0,0,0,0,0,1,0,0,0,1,1,1]
A[11,:] = [0,0,0,0,0,0,0,0,0,1,1,1]
b = np.array([1]*12)
sense = ['>']*12

In [6]:
ipMod = gp.Model()
ipMod_x = ipMod.addMVar(len(obj),vtype=['B']*len(obj))
ipMod_con = ipMod.addMConstrs(A, ipMod_x, sense, b)
ipMod.setMObjective(None,obj,0,sense=gp.GRB.MINIMIZE)
ipMod.Params.OutputFlag = 0
ipMod.optimize()

In [7]:
ipMod.x

[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0]

Answer: SLC which is in 10th position in this list is a Hub in the optimal solution

# Question 4 - Paper Mill

In [8]:
obj = np.array([20,9,12,8,16,4,21])
A = np.zeros((3,7))
#25 inches
A[0,:] = [4,0,0,3,2,1,1]
#37 inches
A[1,:] = [0,3,0,1,0,1,2]
#54 inches
A[2,:] = [0,0,2,0,1,1,0]
b = np.array([233,148,106])
sense = ['>']*3

In [9]:
ipMod = gp.Model()
ipMod_x = ipMod.addMVar(len(obj),vtype=['I']*len(obj)) 
ipMod_con = ipMod.addMConstrs(A, ipMod_x, sense, b)
ipMod.setMObjective(None,obj,0,sense=gp.GRB.MINIMIZE)

ipMod.Params.OutputFlag = 0 
ipMod.optimize()

In [10]:
ipMod_x.x 

array([  0.,  -0.,  -0.,  42.,  -0., 107.,  -0.])

Answer: 42 rolls needs to be cut into the pattern such that there are 3 cuts of 25 inches, and 1 cut of 37 inches 

# Question 5 - Daysoff scheduling

In [11]:
#Minimizing cost of employement
obj = np.array([330,300,330,360,360,360,360])
A = np.zeros((7,7))
#Sun-Thurs
A[0,:] = [1,0,0,1,1,1,1]
#Mon-Fri
A[1,:] = [1,1,0,0,1,1,1]
#Tues-Sat
A[2,:] = [1,1,1,0,0,1,1]
#Wed-Sun
A[3,:] = [1,1,1,1,0,0,1]
#Thurs-Mon
A[4,:] = [1,1,1,1,1,0,0]
#Fri-Tue
A[5,:] = [0,1,1,1,1,1,0]
#Sat-Wed
A[6,:] = [0,0,1,1,1,1,1]

#Requirement
b = np.array([5,13,12,10,14,8,6])
sense = ['>']*7
print(A,b)

[[1. 0. 0. 1. 1. 1. 1.]
 [1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1.]
 [1. 1. 1. 1. 0. 0. 1.]
 [1. 1. 1. 1. 1. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1. 1. 1.]] [ 5 13 12 10 14  8  6]


In [12]:
ipMod = gp.Model()
ipMod_x = ipMod.addMVar(len(obj),vtype=['I']*len(obj))
ipMod_con = ipMod.addMConstrs(A, ipMod_x, sense, b)
ipMod.setMObjective(None,obj,0,sense=gp.GRB.MINIMIZE)
ipMod.Params.OutputFlag = 0 
ipMod.optimize()

In [13]:
ipMod.x

[1.0, 8.0, 2.0, -0.0, 3.0, 1.0, -0.0]

8 employees needs to work from Monday-friday